# Generated by Django 5.0.1 on 2025-02-09 11:49

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discount')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('DO', 'Direct Price'), ('DP', 'Discount Off'), ('PC', 'One Time Use'), ('EC', 'Multy Time Use')], default='DP', max_length=2, verbose_name='Mode')),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limit Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Price')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
    ]
